<table align="center" width=100%>
    <tr>
        <td>
            <div align="center">
                <font color="#21618C" size=24px>
                    <b>Bengaluru Restaurants Data cleaning and normalization
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

![Restaurant](images/Restaurant.jpg)

In [ ]:
import pandas as pd
import numpy as np

In [2]:
file_path = r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis Project\Dataset-Zomato\Zomato.CSV"
df = pd.read_csv(file_path)

In [3]:
df.shape

(10000, 18)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   10000 non-null  int64
 1   url                          10000 non-null  object
 2   address                      10000 non-null  object
 3   name                         10000 non-null  object
 4   online_order                 10000 non-null  object
 5   book_table                   10000 non-null  object
 6   rate                         8528 non-null   object
 7   votes                        10000 non-null  int64
 8   phone                        9764 non-null   object
 9   location                     9997 non-null   object
 10  rest_type                    9953 non-null   object
 11  dish_liked                   4642 non-null   object
 12  cuisines                     9995 non-null   object
 13  approx_cost(for two people)  9941 non-null   object
 14  reviews_list                 10000 non-null  object
 15  menu_item                    10000 non-null  object
 16  listed_in(type)              10000 non-null  object
 17  listed_in(city)              10000 non-null  object
dtypes: int64(2), object(16)
memory usage: 1.4+ MB

In [5]:
df.head()

,Unnamed: 0,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,14221,https://www.zomato.com/bangalore/shree-ranga-v...,"366, Hosur Main Road, Attibele, Anekal Taluk, ...",Shree Ranga Vilas,No,No,3.2/5,7,080 29765044,Electronic City,Casual Dining,NaN,"North Indian, South Indian, Chinese, Juices",500,"[('Rated 3.0', 'RATED\n Typical South Indian ...",[],Dine-out,Electronic City
1,43422,https://www.zomato.com/bangalore/sphyre-gatewa...,"Gateway Hotel, 66, Residency Road, Bangalore",Sphyre - Gateway Hotel,No,No,3.6 /5,45,+91 9886643495\n+91 9898780004,Residency Road,Lounge,NaN,Finger Food,"1,700","[('Rated 1.0', 'RATED\n Expected a good night...",[],Dine-out,MG Road
2,16032,https://www.zomato.com/bangalore/popular-baker...,"19, BDA Complex, HSR, Bangalore",Popular Bakery,No,No,3.7/5,36,+91 8105834605\r\n080 25722488,HSR,"Dessert Parlor, Bakery",NaN,"Desserts, Bakery",600,"[('Rated 5.0', ""RATED\n This outlet is in HSR...",[],Delivery,HSR
3,51635,https://www.zomato.com/bangalore/thai-chinese-...,"7, Anurhh Arcade, Hoodi Road, Kodigehalli Road...",Thai & Chinese Fast Food,No,No,3.4 /5,7,+91 9206260085\n+91 7619416923,KR Puram,Quick Bites,NaN,"Chinese, Thai",400,"[('Rated 5.0', 'RATED\n Its Looking delicious...",[],Dine-out,Whitefield
4,23424,https://www.zomato.com/bangalore/grill-on-whee...,"Kothanuru Main Road, Puttenahalli Road, Natara...",Grill On Wheels,No,No,NEW,0,+91 9901979901,JP Nagar,Quick Bites,NaN,"North Indian, Chinese, BBQ, Arabian, Fast Food",400,[],[],Dine-out,JP Nagar

In [34]:
df['listed_in(city)'].unique()

array(['Electronic City', 'MG Road', 'HSR', 'Whitefield', 'JP Nagar',
       'Frazer Town', 'BTM', 'Koramangala 7th Block',
       'Koramangala 4th Block', 'Koramangala 6th Block', 'Malleshwaram',
       'Bellandur', 'Kammanahalli', 'Church Street', 'Jayanagar',
       'Sarjapur Road', 'Basavanagudi', 'Koramangala 5th Block',
       'Residency Road', 'Lavelle Road', 'Old Airport Road',
       'Brigade Road', 'Kalyan Nagar', 'Indiranagar', 'New BEL Road',
       'Bannerghatta Road', 'Marathahalli', 'Rajajinagar', 'Banashankari',
       'Brookefield'], dtype=object)

In [35]:
df['listed_in(city)'].nunique()

30

In [36]:
df['location'].nunique()

89

In [37]:
df.duplicated().sum()

909

In [38]:
df = df.drop_duplicates()

In [39]:
df.duplicated().sum()

0

In [40]:
df.isnull().sum()

Unnamed: 0                        0
url                               0
address                           0
name                              0
online_order                      0
book_table                        0
rate                           1348
votes                             0
phone                           210
location                          3
rest_type                        44
dish_liked                     4867
cuisines                          5
approx_cost(for two people)      54
reviews_list                      0
menu_item                         0
listed_in(type)                   0
listed_in(city)                   0
dtype: int64

# Listing type table

In [42]:
df['listed_in(type)'].duplicated().sum()

9084

In [43]:
df['listed_in(type)'].isnull().sum()

0

In [44]:
df['listed_in(type)'].head()

0    Dine-out
1    Dine-out
2    Delivery
3    Dine-out
4    Dine-out
Name: listed_in(type), dtype: object

In [45]:
df['listed_in(type)'].unique()

array(['Dine-out', 'Delivery', 'Drinks & nightlife', 'Pubs and bars',
       'Cafes', 'Desserts', 'Buffet'], dtype=object)

In [46]:
listing_type_df = df[['listed_in(type)']].drop_duplicates().reset_index(drop=True)
listing_type_df['listing_id'] = listing_type_df.index+1
listing_type_df = listing_type_df[['listing_id', 'listed_in(type)']]

listing_type_df.head()

   listing_id     listed_in(type)
0           1            Dine-out
1           2            Delivery
2           3  Drinks & nightlife
3           4       Pubs and bars
4           5               Cafes

In [47]:
#listing_type_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\listing_type.csv", index=False)

# Listing city table

In [49]:
df['listed_in(city)'].duplicated().sum()

9061

In [50]:
df['listed_in(city)'].isnull().sum()

0

In [51]:
df['listed_in(city)'].head()

0    Electronic City
1            MG Road
2                HSR
3         Whitefield
4           JP Nagar
Name: listed_in(city), dtype: object

In [52]:
listing_city_df = df[['listed_in(city)']].drop_duplicates().reset_index(drop=True)
listing_city_df['listing_city_id'] = listing_city_df.index+1
listing_city_df = listing_city_df[['listing_city_id', 'listed_in(city)']]

listing_city_df.head()

   listing_city_id  listed_in(city)
0                1  Electronic City
1                2          MG Road
2                3              HSR
3                4       Whitefield
4                5         JP Nagar

In [53]:
#listing_city_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\listing_city.csv", index=False)

# Location table

In [55]:
df['location'].duplicated().sum()

9001

In [56]:
df['location'].isnull().sum()

3

In [57]:
df['location'].fillna('Unknown', inplace = True)

In [58]:
location_df = df[['location']].drop_duplicates().reset_index(drop=True)
location_df['location_id'] = location_df.index + 1
location_df = location_df[['location_id', 'location']]

location_df.head()

   location_id         location
0            1  Electronic City
1            2   Residency Road
2            3              HSR
3            4         KR Puram
4            5         JP Nagar

In [59]:
location_df.isnull().sum()

location_id    0
location       0
dtype: int64

In [60]:
location_df[location_df['location'] == 'Unknown']

    location_id location
84           85  Unknown

In [61]:
location_df['location_id'].duplicated().sum()

0

In [62]:
location_df.duplicated().sum()

0

In [63]:
#location_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\location.csv", index=False)

# Restaurant type table

In [65]:
df['rest_type'].duplicated().sum()

9008

In [66]:
df['rest_type'].isnull().sum()

44

In [67]:
df['rest_type'].fillna('Unknown', inplace = True)

In [68]:
rest_type_df = df[['rest_type']].drop_duplicates().reset_index(drop = True)
rest_type_df['rest_type_id'] = rest_type_df.index + 1
rest_type_df = rest_type_df[['rest_type_id', 'rest_type']]

rest_type_df.head()

   rest_type_id               rest_type
0             1           Casual Dining
1             2                  Lounge
2             3  Dessert Parlor, Bakery
3             4             Quick Bites
4             5                  Bakery

In [69]:
rest_type_df.isnull().sum()

rest_type_id    0
rest_type       0
dtype: int64

In [70]:
rest_type_df[rest_type_df['rest_type'] == 'Unknown']

    rest_type_id rest_type
26            27   Unknown

In [71]:
rest_type_df['rest_type_id'].duplicated().sum()

0

In [72]:
rest_type_df.duplicated().sum()

0

In [73]:
#rest_type_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\rest_type.csv", index=False)

# Cuisine table

In [75]:
df['cuisines'].fillna('Unknown', inplace = True)

In [76]:
df['cuisines'].isnull().sum()

0

In [77]:
cuisine_series = df['cuisines'].str.split(',')
all_cuisines = set()
for sublist in cuisine_series:
    if isinstance(sublist, list):
        for cuisine in sublist:
            all_cuisines.add(cuisine.strip())
cuisine_df = pd.DataFrame(list(all_cuisines), columns=['cuisines']).reset_index(drop=True)
cuisine_df['cuisine_id'] = cuisine_df.index + 1
cuisine_df = cuisine_df[['cuisine_id', 'cuisines']]

cuisine_df.head()

   cuisine_id    cuisines
0           1   Malaysian
1           2     Bengali
2           3      Bakery
3           4     Turkish
4           5  Hyderabadi

In [78]:
cuisine_df[cuisine_df['cuisines'] == 'Unknown']

    cuisine_id cuisines
38          39  Unknown

In [79]:
cuisine_df['cuisine_id'].duplicated().sum()

0

In [80]:
cuisine_df.duplicated().sum()

0

In [81]:
#cuisine_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\cuisine.csv", index=False)

# Restaurant table

In [83]:
df['Unnamed: 0'].duplicated().sum()

0

In [84]:
df.rename(columns = {'Unnamed: 0': 'restaurant_id'}, inplace = True)

In [110]:
# Merge location & restaurant type IDs
restaurant_df = df[['restaurant_id', 'name', 'address', 'phone', 'url', 'location', 'rest_type', 'listed_in(type)', 'listed_in(city)', 'approx_cost(for two people)']].copy()
restaurant_df = restaurant_df.merge(location_df, on='location', how='left')
restaurant_df = restaurant_df.merge(rest_type_df, on='rest_type', how='left')
restaurant_df = restaurant_df.merge(listing_type_df, on='listed_in(type)', how='left')
restaurant_df = restaurant_df.merge(listing_city_df, on='listed_in(city)', how='left')
restaurant_df_final = restaurant_df[['restaurant_id', 'name', 'address', 'phone', 'url', 'location_id', 'rest_type_id', 'listing_id', 'listing_city_id', 'approx_cost(for two people)']]
restaurant_df_final.rename(columns={'approx_cost(for two people)': 'cost_for_two'}, inplace=True)
restaurant_df_final = restaurant_df_final[['restaurant_id', 'location_id', 'rest_type_id', 'listing_id', 'listing_city_id', 'name', 'address', 'phone', 'url', 'cost_for_two']]

restaurant_df_final.head()

C:\Users\PC\AppData\Local\Temp\ipykernel_5056\4200145848.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  restaurant_df_final.rename(columns={'approx_cost(for two people)': 'cost_for_two'}, inplace=True)

,restaurant_id,location_id,rest_type_id,listing_id,listing_city_id,name,address,phone,url,cost_for_two
0,14221,1,1,1,1,Shree Ranga Vilas,"366, Hosur Main Road, Attibele, Anekal Taluk, ...",080 29765044,https://www.zomato.com/bangalore/shree-ranga-v...,500
1,43422,2,2,1,2,Sphyre - Gateway Hotel,"Gateway Hotel, 66, Residency Road, Bangalore",+91 9886643495\n+91 9898780004,https://www.zomato.com/bangalore/sphyre-gatewa...,"1,700"
2,16032,3,3,2,3,Popular Bakery,"19, BDA Complex, HSR, Bangalore",+91 8105834605\r\n080 25722488,https://www.zomato.com/bangalore/popular-baker...,600
3,51635,4,4,1,4,Thai & Chinese Fast Food,"7, Anurhh Arcade, Hoodi Road, Kodigehalli Road...",+91 9206260085\n+91 7619416923,https://www.zomato.com/bangalore/thai-chinese-...,400
4,23424,5,4,1,5,Grill On Wheels,"Kothanuru Main Road, Puttenahalli Road, Natara...",+91 9901979901,https://www.zomato.com/bangalore/grill-on-whee...,400

In [112]:
restaurant_df_final.duplicated().sum()

0

In [114]:
restaurant_df_final['location_id'].duplicated().sum()

9001

In [116]:
restaurant_df_final['rest_type_id'].duplicated().sum()

9008

In [118]:
restaurant_df_final['restaurant_id'].duplicated().sum()

0

In [120]:
restaurant_df_final.isnull().sum()

restaurant_id        0
location_id          0
rest_type_id         0
listing_id           0
listing_city_id      0
name                 0
address              0
phone              210
url                  0
cost_for_two        54
dtype: int64

In [ ]:
#restaurant_df_final.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\restaurant.csv", index=False)

# Restaurant-Cuisine Mapping Table

In [ ]:
restaurant_cuisine_rows = []
for idx, row in df[['restaurant_id', 'cuisines']].iterrows():
    cuisines = row['cuisines'].split(', ')
    for cuisine in cuisines:
        cuisine_id = cuisine_df.loc[cuisine_df['cuisines'] == cuisine.strip(), 'cuisine_id'].values[0]
        restaurant_cuisine_rows.append({'restaurant_id': row['restaurant_id'], 'cuisine_id': cuisine_id})
restaurant_cuisine_df = pd.DataFrame(restaurant_cuisine_rows)

restaurant_cuisine_df.head()

In [ ]:
restaurant_cuisine_df.duplicated().sum()

In [ ]:
restaurant_cuisine_df['restaurant_id'].duplicated().sum()

In [ ]:
restaurant_cuisine_df['cuisine_id'].duplicated().sum()

In [ ]:
restaurant_cuisine_df.isnull().sum()

In [ ]:
#restaurant_cuisine_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\restaurant_cuisine.csv", index=False)

# Services Table

In [ ]:
services_df = df[['restaurant_id', 'online_order', 'book_table']]

services_df.head()

In [ ]:
services_df.duplicated().sum()

In [ ]:
services_df['restaurant_id'].duplicated().sum()

In [ ]:
#services_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\services.csv", index=False)

# Rating table

In [ ]:
rating_df = df[['restaurant_id', 'rate', 'votes']]

rating_df.head()

In [ ]:
rating_df['restaurant_id'].duplicated().sum()

In [ ]:
rating_df.duplicated().sum()

In [ ]:
rating_df.isnull().sum()

In [ ]:
#rating_df.to_csv(r"D:\Data Analytics Project\Bengaluru Restaurant Trends Analysis\Datasets.csv\rating.csv", index=False)